export const countries = {
  "RO": "România",
  "AF": "Afganistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AD": "Andorra",
  "AO": "Angola",
  "AG": "Antigua și Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaidjan",
  "BS": "Bahamas",
  "BH": "Bahrein",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgia",
  "BZ": "Belize",
  "BJ": "Benin",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia și Herțegovina",
  "BW": "Botswana",
  "BR": "Brazilia",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Capul Verde",
  "KH": "Cambodgia",
  "CM": "Camerun",
  "CA": "Canada",
  "CF": "Republica Centrafricană",
  "TD": "Ciad",
  "CL": "Chile",
  "CN": "China",
  "CO": "Columbia",
  "KM": "Comore",
  "CG": "Congo",
  "CD": "Republica Democrată Congo",
  "CR": "Costa Rica",
  "CI": "Coasta de Fildeș",
  "HR": "Croația",
  "CU": "Cuba",
  "CY": "Cipru",
  "CZ": "Cehia",
  "DK": "Danemarca",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Republica Dominicană",
  "EC": "Ecuador",
  "EG": "Egipt",
  "SV": "El Salvador",
  "GQ": "Guineea Ecuatorială",
  "ER": "Eritreea",
  "EE": "Estonia",
  "SZ": "Eswatini",
  "ET": "Etiopia",
  "FJ": "Fiji",
  "FI": "Finlanda",
  "FR": "Franța",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germania",
  "GH": "Ghana",
  "GR": "Grecia",
  "GD": "Grenada",
  "GT": "Guatemala",
  "GN": "Guineea",
  "GW": "Guineea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HN": "Honduras",
  "HU": "Ungaria",
  "IS": "Islanda",
  "IN": "India",
  "ID": "Indonezia",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irlanda",
  "IL": "Israel",
  "IT": "Italia",
  "JM": "Jamaica",
  "JP": "Japonia",
  "JO": "Iordania",
  "KZ": "Kazahstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Coreea de Nord",
  "KR": "Coreea de Sud",
  "KW": "Kuweit",
  "KG": "Kârgâzstan",
  "LA": "Laos",
  "LV": "Letonia",
  "LB": "Liban",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libia",
  "LI": "Liechtenstein",
  "LT": "Lituania",
  "LU": "Luxemburg",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaezia",
  "MV": "Maldive",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Insulele Marshall",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "MX": "Mexic",
  "FM": "Micronezia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Muntenegru",
  "MA": "Maroc",
  "MZ": "Mozambic",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Țările de Jos",
  "NZ": "Noua Zeelandă",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "MK": "Macedonia de Nord",
  "NO": "Norvegia",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua Noua Guinee",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Filipine",
  "PL": "Polonia",
  "PT": "Portugalia",
  "QA": "Qatar",
  "RU": "Rusia",
  "RW": "Rwanda",
  "KN": "Saint Kitts și Nevis",
  "LC": "Saint Lucia",
  "VC": "Saint Vincent și Grenadine",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé și Príncipe",
  "SA": "Arabia Saudită",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovacia",
  "SI": "Slovenia",
  "SB": "Insulele Solomon",
  "SO": "Somalia",
  "ZA": "Africa de Sud",
  "SS": "Sudanul de Sud",
  "ES": "Spania",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SE": "Suedia",
  "CH": "Elveția",
  "SY": "Siria",
  "TJ": "Tadjikistan",
  "TZ": "Tanzania",
  "TH": "Thailanda",
  "TL": "Timorul de Est",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad și Tobago",
  "TN": "Tunisia",
  "TR": "Turcia",
  "TM": "Turkmenistan",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ucraina",
  "AE": "Emiratele Arabe Unite",
  "GB": "Regatul Unit",
  "US": "Statele Unite ale Americii",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};