export const counties_ro = {
  "AB":"Alba",
  "AR":"Arad",
  "AG":"Argeș",
  "BC":"Bacău",
  "BH":"Bihor",
  "BN":"Bistrița-Năsăud",
  "BT":"Botoșani",
  "BV":"Brașov",
  "BR":"Brăila",
  "BZ":"Buzău",
  "CS":"Caraș-Severin",
  "CL":"Călărași",
  "CJ":"Cluj",
  "CT":"Constanța",
  "CV":"Covasna",
  "DB":"Dâmbovița",
  "DJ":"Dolj",
  "GL":"Galați",
  "GR":"Giurgiu",
  "GJ":"Gorj",
  "HR":"Harghita",
  "HD":"Hunedoara",
  "IL":"Ialomița",
  "IS":"Iași",
  "IF":"Ilfov",
  "MM":"Maramureș",
  "MH":"Mehedinți",
  "MS":"Mureș",
  "NT":"Neamț",
  "OT":"Olt",
  "PH":"Prahova",
  "SM":"Satu Mare",
  "SJ":"Sălaj",
  "SB":"Sibiu",
  "SV":"Suceava",
  "TR":"Teleorman",
  "TM":"Timiș",
  "TL":"Tulcea",
  "VS":"Vaslui",
  "VL":"Vâlcea",
  "VN":"Vrancea",
  "S1":"Sector 1",
  "S2":"Sector 2",
  "S3":"Sector 3",
  "S4":"Sector 4",
  "S5":"Sector 5",
  "S6":"Sector 6",
}
